## Using OpenCV2 remove background of the images

In [1]:
import glob
from PIL import Image

### Used https://www.remove.bg/upload to remove bg from the images.

### Convert all .png image files with white background to .jpg

In [19]:
path = './fg/*.png'
count = 0
for filename in glob.glob(path):
    img = Image.open(filename)
    count = count +1
    print("{} Converting {} ".format(count,filename))
    fn = filename.split(".")[1]
    rgb_img = img.convert('RGB')
    rgb_img.save('.'+fn+'.jpg')

1 Converting ./fg/img_fg_031-removebg-preview.png 


### A few images are downloaded with white background so does not need to be converted to. jpg format.

### Need to be consolidated into a single folder

In [3]:
import os
import shutil

source = './fg-raw'
target = './fg'

src_files = os.listdir(source)
trgt_files = os.listdir(target)

for file_name in src_files:
    full_file_name = os.path.join(source, file_name)
    if os.path.isfile(full_file_name):
        if file_name not in trgt_files:
            print("The {} is not in target".format(file_name))
            shutil.copy(full_file_name, target)
        
        else:
            print("All the files are copied from source to target")
            break



All the files are copied from source to target


### Masking the images

In [20]:
from PIL import Image, ImageOps
import glob

source_dir_path = './fg/*.jpg'
target_dir_path = './fg-mask/'

for file in glob.glob(source_dir_path):
    filename = file.split('/')[2]
    im = Image.open(file).convert('RGB')
    im_gray_scale = im.convert('L')
    im_invert = ImageOps.invert(im_gray_scale)
    print("Saving image {} into dir {}".format(filename,target_dir_path))
    im_invert.save(target_dir_path+filename)


Saving image img_fg_051.jpg into dir ./fg-mask/
Saving image img_fg_004.jpg into dir ./fg-mask/
Saving image img_fg_017.jpg into dir ./fg-mask/
Saving image img_fg_068.jpg into dir ./fg-mask/
Saving image img_fg_014.jpg into dir ./fg-mask/
Saving image img_fg_096.jpg into dir ./fg-mask/
Saving image img_fg_030.jpg into dir ./fg-mask/
Saving image img_fg_026.jpg into dir ./fg-mask/
Saving image img_fg_100.jpg into dir ./fg-mask/
Saving image img_fg_069.jpg into dir ./fg-mask/
Saving image img_fg_093.jpg into dir ./fg-mask/
Saving image img_fg_038.jpg into dir ./fg-mask/
Saving image img_fg_009.jpg into dir ./fg-mask/
Saving image img_fg_075.jpg into dir ./fg-mask/
Saving image img_fg_078.jpg into dir ./fg-mask/
Saving image img_fg_083.jpg into dir ./fg-mask/
Saving image img_fg_048.jpg into dir ./fg-mask/
Saving image img_fg_087.jpg into dir ./fg-mask/
Saving image img_fg_008.jpg into dir ./fg-mask/
Saving image img_fg_023.jpg into dir ./fg-mask/
Saving image img_fg_043.jpg into dir ./f

### Flipping images - mirroring 

In [21]:
from PIL import Image, ImageOps
import glob

source_dir_path = './fg/*.jpg'
target_dir_path = './fg-flip/'

for file in glob.glob(source_dir_path):
    filename = file.split('/')[2]
    im = Image.open(file).convert('RGB')
    im_flip = ImageOps.mirror(im)
    print("Saving image {} into dir {}".format(filename,target_dir_path))
    im_flip.save(target_dir_path+filename)

Saving image img_fg_051.jpg into dir ./fg-flip/
Saving image img_fg_004.jpg into dir ./fg-flip/
Saving image img_fg_017.jpg into dir ./fg-flip/
Saving image img_fg_068.jpg into dir ./fg-flip/
Saving image img_fg_014.jpg into dir ./fg-flip/
Saving image img_fg_096.jpg into dir ./fg-flip/
Saving image img_fg_030.jpg into dir ./fg-flip/
Saving image img_fg_026.jpg into dir ./fg-flip/
Saving image img_fg_100.jpg into dir ./fg-flip/
Saving image img_fg_069.jpg into dir ./fg-flip/
Saving image img_fg_093.jpg into dir ./fg-flip/
Saving image img_fg_038.jpg into dir ./fg-flip/
Saving image img_fg_009.jpg into dir ./fg-flip/
Saving image img_fg_075.jpg into dir ./fg-flip/
Saving image img_fg_078.jpg into dir ./fg-flip/
Saving image img_fg_083.jpg into dir ./fg-flip/
Saving image img_fg_048.jpg into dir ./fg-flip/
Saving image img_fg_087.jpg into dir ./fg-flip/
Saving image img_fg_008.jpg into dir ./fg-flip/
Saving image img_fg_023.jpg into dir ./fg-flip/
Saving image img_fg_043.jpg into dir ./f

### Make sure all the images have RGB channels

In [28]:
from PIL import Image, ImageOps
import glob

source_dir_path = './fg/*.jpg'

for file in glob.glob(source_dir_path):
    img = Image.open(file)
    print("Image {} has {} channels".format(file, len(img.getbands())))

Image ./fg/img_fg_051.jpg has 3 channels
Image ./fg/img_fg_004.jpg has 3 channels
Image ./fg/img_fg_017.jpg has 3 channels
Image ./fg/img_fg_068.jpg has 3 channels
Image ./fg/img_fg_014.jpg has 3 channels
Image ./fg/img_fg_096.jpg has 3 channels
Image ./fg/img_fg_030.jpg has 3 channels
Image ./fg/img_fg_026.jpg has 3 channels
Image ./fg/img_fg_100.jpg has 3 channels
Image ./fg/img_fg_069.jpg has 3 channels
Image ./fg/img_fg_093.jpg has 3 channels
Image ./fg/img_fg_038.jpg has 3 channels
Image ./fg/img_fg_009.jpg has 3 channels
Image ./fg/img_fg_075.jpg has 3 channels
Image ./fg/img_fg_078.jpg has 3 channels
Image ./fg/img_fg_083.jpg has 3 channels
Image ./fg/img_fg_048.jpg has 3 channels
Image ./fg/img_fg_087.jpg has 3 channels
Image ./fg/img_fg_008.jpg has 3 channels
Image ./fg/img_fg_023.jpg has 3 channels
Image ./fg/img_fg_043.jpg has 3 channels
Image ./fg/img_fg_097.jpg has 3 channels
Image ./fg/img_fg_049.jpg has 3 channels
Image ./fg/img_fg_034.jpg has 3 channels
Image ./fg/img_f

### Overlaying images onto one another

In [40]:
from PIL import Image, ImageOps

fg_img_dir = './fg/'
bg_img_dir = './bg/'

target_dir = './fg-bg/'
bg = Image.open(bg_img_dir+"img_bg_001.jpg")
fg = Image.open(fg_img_dir+"img_fg_001.jpg")

bg = bg.convert("RGBA")
fg = fg.convert("RGBA")

bg1 = bg.resize((250,250))
fg1 = fg.resize((250,250))

bg1.show()
fg1.show()
fg_bg = Image.blend(fg1, bg1, 1.0)
fg_bg.save(target_dir+"img_fg-bg_001.png")

In [15]:
import cv2

img = cv2.imread('./fg/img_fg_001.jpg')
w, h, d = img.shape
i, j, k = 0,0,0
while i < w:
    i=i+1
    if img.any() < 255:
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183


In [1]:
import cv2

fg_img_dir = './fg/'
bg_img_dir = './bg/'
# Load two images
img1 = cv2.imread(bg_img_dir+'img_bg_001.jpg')
img2 = cv2.imread(fg_img_dir+'img_fg_001.jpg')

img2 = cv2.resize(img2,(100,100),interpolation=cv2.INTER_AREA)
# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols]
# Now create a mask of logo and create its inverse mask also
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)
# Now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
# Take only region of logo from logo image.
img2_fg = cv2.bitwise_and(img2,img2,mask = mask)
# Put logo in ROI and modify the main image
dst = cv2.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst
cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2

fg_img_dir = './fg/'
img2 = cv2.imread(fg_img_dir+'img_fg_001.jpg')
im = img2-[[255, 255, 255]]
cv2.imshow('res',im)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.2.0) /io/opencv/modules/highgui/src/precomp.hpp:137: error: (-215:Assertion failed) src_depth != CV_16F && src_depth != CV_32S in function 'convertToShow'


In [4]:
from PIL import Image

img = Image.open('./fg/img_fg_001.jpg')
img = img.convert("RGB")
datas = img.getdata()

newData = []
for item in datas:
    if item[0] == 255 and item[1] == 255 and item[2] == 255:
        newData.append((255, 255, 255, 0))
    else:
        if item[0] > 150:
            newData.append((0, 0, 0, 255))
        else:
            newData.append(item)
            print(item)


img.putdata(newData)
img.save("./fg-test/img_fg_001.png", "PNG")


(149, 146, 139)
(140, 137, 130)
(130, 127, 118)
(129, 125, 116)
(133, 129, 120)
(137, 133, 124)
(135, 131, 122)
(132, 128, 119)
(150, 151, 145)
(149, 149, 141)
(131, 128, 119)
(137, 134, 125)
(133, 129, 120)
(126, 122, 113)
(126, 119, 109)
(127, 120, 110)
(129, 122, 112)
(129, 122, 112)
(129, 122, 112)
(126, 127, 119)
(112, 109, 100)
(128, 125, 116)
(122, 118, 107)
(122, 118, 107)
(123, 116, 106)
(120, 114, 102)
(117, 109, 98)
(117, 109, 98)
(120, 112, 101)
(124, 116, 105)
(122, 124, 113)
(119, 121, 110)
(143, 143, 133)
(141, 139, 127)
(103, 101, 89)
(131, 127, 116)
(110, 106, 94)
(117, 111, 99)
(122, 114, 103)
(118, 110, 99)
(113, 103, 91)
(111, 101, 89)
(116, 106, 94)
(122, 112, 100)
(134, 136, 125)
(121, 123, 112)
(143, 145, 134)
(143, 143, 131)
(111, 111, 99)
(114, 112, 100)
(99, 95, 83)
(110, 106, 94)
(108, 102, 90)
(115, 107, 94)
(120, 112, 99)
(120, 110, 98)
(114, 104, 92)
(113, 101, 89)
(117, 105, 91)
(122, 110, 96)
(125, 127, 114)
(128, 130, 117)
(132, 134, 121)
(150, 152, 141

(98, 95, 86)
(43, 35, 32)
(61, 51, 50)
(132, 120, 122)
(97, 98, 102)
(31, 34, 43)
(35, 36, 54)
(94, 94, 118)
(44, 45, 73)
(62, 63, 93)
(36, 53, 81)
(41, 61, 86)
(52, 72, 96)
(63, 86, 104)
(71, 97, 112)
(71, 97, 114)
(56, 83, 104)
(40, 66, 91)
(51, 76, 107)
(53, 77, 113)
(62, 84, 121)
(72, 95, 129)
(84, 105, 136)
(84, 104, 129)
(6, 24, 44)
(18, 37, 52)
(38, 29, 72)
(71, 63, 102)
(148, 137, 135)
(121, 107, 107)
(142, 126, 129)
(80, 80, 90)
(60, 61, 79)
(64, 64, 88)
(39, 39, 67)
(42, 41, 72)
(18, 35, 63)
(35, 55, 80)
(53, 73, 97)
(58, 81, 99)
(57, 83, 98)
(56, 82, 99)
(43, 70, 89)
(29, 55, 80)
(18, 43, 74)
(52, 76, 110)
(65, 87, 124)
(87, 107, 142)
(72, 91, 121)
(72, 90, 114)
(0, 18, 35)
(23, 40, 56)
(42, 33, 78)
(36, 28, 69)
(23, 44, 49)
(42, 61, 68)
(44, 61, 71)
(71, 83, 99)
(67, 78, 96)
(46, 58, 80)
(73, 89, 114)
(53, 78, 100)
(31, 62, 83)
(30, 65, 84)
(45, 84, 99)
(56, 94, 107)
(73, 107, 117)
(54, 82, 93)
(6, 30, 40)
(34, 54, 63)
(17, 27, 29)
(50, 58, 60)
(132, 140, 142)
(30, 49, 56)


In [9]:
import glob

path = './fg-test/*.png'
count = 37
for filename in glob.glob(path):
    img = Image.open(filename)
    
   # print("{} Converting {} ".format(count,filename))
    fn = filename.split("/")[2]
    filenm = fn.split("-")[0]
    print(filenm)
    count = count +1
    img.save('./'+filenm+'.png')

fg_70
fg_52
fg_90
fg_40
fg_37
fg_51
fg_92
fg_94
fg_79
fg_65
fg_68
fg_44
fg_46
fg_72
fg_49
fg_61
fg_89
fg_95
fg_82
fg_97
fg_80
fg_64
fg_54
fg_43
fg_42
fg_100
fg_60
fg_47
fg_45
fg_71
fg_62
fg_38
fg_48
fg_67
fg_73
fg_58
fg_78
fg_55
fg_85
fg_50
fg_57
fg_69
fg_41
fg_75
fg_84
fg_83
fg_87
fg_96
fg_81
fg_56
fg_77
fg_53
fg_74
fg_63
fg_99
fg_91
fg_66
fg_98
fg_39
fg_86
fg_76
fg_93
fg_88
fg_59


### Mean and Std Deviation

In [81]:
import glob
from PIL import Image
import numpy as np

root_dir_path = './fg-bg-test/*.png'
sd=[]
mean = []
for filename in glob.glob(root_dir_path):
    img = Image.open(filename)
    imarr = np.array(img,dtype=np.float)
    mean.append(np.mean(imarr))
    sd.append(np.std(imarr))
    


print("Standard Deviation : ",np.std(sd))
print("Mean : ", np.mean(mean))

Standard Deviation :  0.7015340839445372
Mean :  83.10293253968254


In [103]:
import glob
from PIL import Image
path = './fg-bg-test/test/*.png'

for filename in glob.glob(path):
    img = Image.open(filename)
    img = img.resize((640,480), Image.BILINEAR)
    img.save(filename)
    

In [ ]:
# Save output in a directory
idx = 1
counter = 1
for imarr in outputs.copy():
    img = Image.fromarray(imarr)
    filename = 'img_bgfg_'+ counter
    img = img.resize((150,150), Image.BILINEAR)
    img.save(args.output+filename)
    

In [46]:
print("Outputs shape", outputs.shape)
counter = 1
for imarr in outputs:
    imarr.dtype = np.uint8
    print("Output image shape {} and dtype {}".format(imarr.shape,imarr.dtype))
    img = Image.fromarray(imarr)
    img = img.convert('RGB')
    filename = 'img_bgfg_'+ str(counter)+'.png'
    img = img.resize((150,150), Image.BILINEAR)
    print("Saving file : ",filename)
    img.save(args.output+filename)
    counter = counter + 1


(2, 2, 3, 4)
[[[11 12 13 11]
  [21 22 23 24]
  [31 32 33 34]]

 [[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]]
****************


IndexError: too many indices for array

In [ ]:

############# Utils #################
counter = 1
    for imarr in depth_images:
        img = Image.fromarray((imarr * 255).astype(np.uint8))
        filename = 'depth_bg_0_0_fg_'+ str(counter)+'.png'
        img = img.resize((150,150), Image.BILINEAR)
        print("Saving file : ",filename)
        img.save('./output/'+filename)
        counter = counter + 1